# Generated by Django 4.1.7 on 2023-03-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_alter_item_current_bid_alter_item_initial_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='current_bid',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
