# Generated by Django 4.1.7 on 2023-03-28 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0005_bidded_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_bidder',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_bidder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Item_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='bidded_item',
        ),
    ]
